apiVersion: v1
kind: Service
metadata:
  name: engine
  labels:
    app: rockside
    tier: backend
spec:
  ports:
    - port: 9000
  selector:
    app: rockside
    tier: backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rockside-engine-pv-claim
  labels:
    app: rockside
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockside-engine
  labels:
    app: rockside
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockside
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rockside
        tier: backend
    spec:
      volumes:
        - name: rockside-engine-persistent-storage
          persistentVolumeClaim:
            claimName: rockside-engine-pv-claim
      imagePullSecrets:
        - name: private-docker-key
      securityContext:
        runAsGroup: 33
      containers:
        - image: rockside/engine:v0.7.0
          name: rockside-engine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rockside-db
                  key: host
            - name: DB_DATABASE
              value: rockside
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rockside-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rockside-db
                  key: password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: rockside-app-key
                  key: key
            - name: SLAVE_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rockside-slave-token
                  key: token
            - name: SLAVE_AUTHTOKEN_KEY
              value: rockside
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: rockside-config
                  key: app_url
          ports:
            - containerPort: 9000
              name: engine
          volumeMounts:
            - name: rockside-engine-persistent-storage
              mountPath: /var/www/storage/app/public
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/bash",
                    "-c",
                    "php artisan migrate --no-interaction --force && php artisan passport:install --no-interaction",
                  ]
