apiVersion: v1
kind: Service
metadata:
  name: engine
  labels:
    app: rockside
    tier: backend
spec:
  ports:
    - port: 9000
  selector:
    app: rockside
    tier: backend
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rockside-engine-pv-claim
  labels:
    app: rockside
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockside-engine
  labels:
    app: rockside
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockside
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rockside
        tier: backend
    spec:
      volumes:
      - name: rockside-engine-persistent-storage
        persistentVolumeClaim:
          claimName: rockside-engine-pv-claim
      containers:
      - image: rockside/engine
        name: rockside-engine
        env:
        - name: DB_HOST
          value: rockside-mysql 
        - name: DB_DATABASE
          value: rockside
        - name: DB_USERNAME
          value: rockside
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rockside-db-password
              key: password
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: rockside-app-key
              key: key
        - name: SLAVE_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: rockside-slave-token
              key: token
        - name: SLAVE_AUTHTOKEN_KEY
          value: rockside
        ports:
        - containerPort: 9000
          name: engine
        volumeMounts:
        - name: rockside-engine-persistent-storage
          mountPath: /var/www/storage/app/public
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "php artisan migrate:refresh --no-interaction --force && php artisan passport:install --no-interaction"]