---
apiVersion: v1
kind: Service
metadata:
  name: rockside-front
  labels:
    app: rockside
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 4433
      protocol: TCP
      name: https
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: rockside
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockside-front
  labels:
    app: rockside
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockside
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rockside
        tier: frontend
    spec:
      volumes:
        - name: rockside-front-certs-volume
          secret:
            secretName: rockside-front-certs-keys
        - name: rockside-engine-persistent-storage
          persistentVolumeClaim:
            claimName: rockside-engine-pv-claim
      imagePullSecrets:
        - name: private-docker-key
      containers:
        - image: rockside/front:v0.7.0
          name: rockside-front
          env:
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: rockside-config
                  key: app_url
          ports:
            - containerPort: 4433
            - containerPort: 8080
          volumeMounts:
            - name: rockside-front-certs-volume
              mountPath: /etc/rockside/certs
            - name: rockside-engine-persistent-storage
              mountPath: /var/www/storage/app/public
              readOnly: true
