apiVersion: v1
kind: Service
metadata:
  name: rockside-mysql
  labels:
    app: rockside
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: rockside
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rockside-mysql-pv-claim
  labels:
    app: rockside
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockside-mysql
  labels:
    app: rockside
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockside
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rockside
        tier: mysql
    spec:
      volumes:
      - name: rockside-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: rockside-mysql-pv-claim      
      containers:
      - image: mysql:5.7
        name: rockside-mysql
        env:
        - name: MYSQL_DATABASE
          value: rockside
        - name: MYSQL_USER
          value: rockside
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rockside-db-password
              key: password   
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rockside-db-password
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: rockside-mysql-persistent-storage
          mountPath: /var/lib/mysql
      
