apiVersion: v1
kind: Service
metadata:
  name: rockside-scheduler
  labels:
    app: rockside
    tier: scheduler
spec:
  selector:
    app: rockside
    tier: scheduler
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockside-scheduler
  labels:
    app: rockside
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockside
      tier: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rockside
        tier: scheduler
    spec:
      imagePullSecrets:
        - name: private-docker-key
      containers:
        - image: rockside/scheduler:v0.7.0
          name: rockside-scheduler
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rockside-db
                  key: host
            - name: DB_DATABASE
              value: rockside
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rockside-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rockside-db
                  key: password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: rockside-app-key
                  key: key
            - name: SLAVE_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rockside-slave-token
                  key: token
            - name: SLAVE_AUTHTOKEN_KEY
              value: rockside
